export const articles = [
  {
    title: 'Title1',
    articleType: 'Type',
    abstract: 'This is Abstract of this article.',
    authors: ['author1', 'author2', 'author3'],
    releaseDate : new Date(2019, 12, 12),
    tags: ['tag1', 'tag2', 'tag3'],
    refCount: 114,
    downloadCount: 514,
    hasFile: true,
    showFavorite: true,
  },
  {
    title: 'Title2',
    articleType: 'Type',
    abstract: 'This is Abstract of this article.',
    authors: ['author1', 'author2', 'author3'],
    releaseDate : new Date(2019, 12, 12),
    tags: ['tag1', 'tag2', 'tag3'],
    refCount: 114,
    downloadCount: 514,
    hasFile: true,
    showFavorite: true,
  },
  {
    title: 'Title3',
    articleType: 'Type',
    abstract: 'This is Abstract of this article.',
    authors: ['author1', 'author2', 'author3'],
    releaseDate : new Date(2019, 12, 12),
    tags: ['tag1', 'tag2', 'tag3'],
    refCount: 114,
    downloadCount: 514,
    hasFile: true,
    showFavorite: true,
  },
  {
    title: 'Title4',
    articleType: 'Type',
    abstract: 'This is Abstract of this article.',
    authors: ['author1', 'author2', 'author3'],
    releaseDate : new Date(2019, 12, 12),
    tags: ['tag1', 'tag2', 'tag3'],
    refCount: 114,
    downloadCount: 514,
    hasFile: true,
    showFavorite: true,
  },
  {
    title: 'Title5',
    articleType: 'Type',
    abstract: 'This is Abstract of this article.',
    authors: ['author1', 'author2', 'author3'],
    releaseDate : new Date(2019, 12, 12),
    tags: ['tag1', 'tag2', 'tag3'],
    refCount: 114,
    downloadCount: 514,
    hasFile: true,
    showFavorite: true,
  },
  {
    title: 'Title6',
    articleType: 'Type',
    abstract: 'This is Abstract of this article.',
    authors: ['author1', 'author2', 'author3'],
    releaseDate : new Date(2019, 12, 12),
    tags: ['tag1', 'tag2', 'tag3'],
    refCount: 114,
    downloadCount: 514,
    hasFile: true,
    showFavorite: true,
  },
  {
    title: 'Title7',
    articleType: 'Type',
    abstract: 'This is Abstract of this article.',
    authors: ['author1', 'author2', 'author3'],
    releaseDate : new Date(2019, 12, 12),
    tags: ['tag1', 'tag2', 'tag3'],
    refCount: 114,
    downloadCount: 514,
    hasFile: true,
    showFavorite: true,
  },  {
    title: 'Title8',
    articleType: 'Type',
    abstract: 'This is Abstract of this article.',
    authors: ['author1', 'author2', 'author3'],
    releaseDate : new Date(2019, 12, 12),
    tags: ['tag1', 'tag2', 'tag3'],
    refCount: 114,
    downloadCount: 514,
    hasFile: true,
    showFavorite: true,
  },
  {
    title: 'Title9',
    articleType: 'Type',
    abstract: 'This is Abstract of this article.',
    authors: ['author1', 'author2', 'author3'],
    releaseDate : new Date(2019, 12, 12),
    tags: ['tag1', 'tag2', 'tag3'],
    refCount: 114,
    downloadCount: 514,
    hasFile: true,
    showFavorite: true,
  },
  {
    title: 'Title10',
    articleType: 'Type',
    abstract: 'This is Abstract of this article.',
    authors: ['author1', 'author2', 'author3'],
    releaseDate : new Date(2019, 12, 12),
    tags: ['tag1', 'tag2', 'tag3'],
    refCount: 114,
    downloadCount: 514,
    hasFile: true,
    showFavorite: true,
  },
  {
    title: 'Title11',
    articleType: 'Type',
    abstract: 'This is Abstract of this article.',
    authors: ['author1', 'author2', 'author3'],
    releaseDate : new Date(2019, 12, 12),
    tags: ['tag1', 'tag2', 'tag3'],
    refCount: 114,
    downloadCount: 514,
    hasFile: true,
    showFavorite: true,
  },
];
